version: "3.1"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${ROOT_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PWD: ${MONGO_PWD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}

    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - ./mongo_init/mongo-entrypoint.sh:/docker-entrypoint-initdb.d/mongo-entrypoint.sh:ro
volumes:
  mongodata:
